name: Ruff and Mypy checks

on: push

jobs:
  ruff-and-mypy-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy ruff .

      - name: Run mypy
        run: mypy

      - name: Run ruff
        run: ruff check